# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DKSkynetDemo' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for DKSkynetDemo

  pod 'DKSkynet', :path=>'../'
  pod 'AFNetworking'
  
  target 'DKSkynetDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DKSkynetDemoUITests' do
    # Pods for testing
  end

end
